### ISSUE TITLE
'Bad Gateway' error at /login

### ISSUE THREAD

**Issue by ChrisStonebackTR** [hassio-addons/addon-nginx-proxy-manager#120]
# Problem/Motivation
After upgrading to v0.8.0, when I try to login to nginx at the /login page, I click the 'Sign In' button and just get a "Bad Gateway" error message under the password prompt and returns to the login page.

## Expected behavior
After entering correct credentials, it should login and take me to the nginx administration page.

## Actual behavior
Additionally there are errors in the log visible in the Nginx proxy manager addon in Hassio (not sure if it is related or not)

![image](https://user-images.githubusercontent.com/61333013/97097501-2259e700-163f-11eb-8427-45979f58bf3b.png)

```
[02:17:50] INFO: Starting the Manager...
[10/24/2020] [9:17:59 PM] [Global   ] › ✖  error     Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js Error: Cannot find module '../global/certbot-dns-plugins'
Require stack:
- /opt/nginx-proxy-manager/internal/certificate.js
- /opt/nginx-proxy-manager/internal/proxy-host.js
- /opt/nginx-proxy-manager/internal/report.js
- /opt/nginx-proxy-manager/routes/api/reports.js
- /opt/nginx-proxy-manager/routes/api/main.js
- /opt/nginx-proxy-manager/app.js
- /opt/nginx-proxy-manager/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/nginx-proxy-manager/internal/certificate.js:16:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/nginx-proxy-manager/internal/certificate.js',
    '/opt/nginx-proxy-manager/internal/proxy-host.js',
    '/opt/nginx-proxy-manager/internal/report.js',
    '/opt/nginx-proxy-manager/routes/api/reports.js',
    '/opt/nginx-proxy-manager/routes/api/main.js',
    '/opt/nginx-proxy-manager/app.js',
    '/opt/nginx-proxy-manager/index.js'
  ]
}
```

## Steps to reproduce

Try to login to the /login page

**Comment by moto3001** [comment]
Already an issue: #117   Currently being worked on.

**Comment by frenck** [comment]
Duplicate of #117
